apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      app: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-user
    spec:
     containers:
     - name: backend-user
       image: billelbenoudjit/udagram-api-user
       ports:
       - containerPort: 8080
       envFrom:
       - configMapRef:
          name: udagram-configmap
       - secretRef:
          name: udagram-env-secret
       volumeMounts:
       - mountPath: "/root/.aws/"
         name: aws-creds
     volumes:
     - name: aws-creds
       configMap:
        name: aws-creds